### ISSUE TITLE
Make it possible to link to specific versions / releases

### ISSUE THREAD

**Issue by q0rban** [cutenode/1x.engineer#109]
It would be helpful to those who resonate with this project to be able to link to specific versions. That way they can have reviewed what the list says at that time, be able to say so in some public form, "yep, this is me!" and move on without fear that it will change in the future to say something they are against. For example, someone may read the list as it stands today, and then plop the `1x.engineer` link somewhere on a public facing social network profile, proclaiming, "yep, this is me!" and then come back several years later and realize there are things they strongly disagree with that have made its way onto the list.

**Comment by cherscarlett** [comment]
Hi @q0rban - this request feels a bit out of scope for this project. I encourage you to fork the project if/when it reaches a state that you don't agree with. 💓
