### ISSUE TITLE
Request for enhancement of 1x site

### ISSUE THREAD

**Issue by Tropicalrambler** [cutenode/1x.engineer#13]
Would it be possible to add the 1x programmer meme, namely the dog part, so that when tempted to multiply him/her self by 10, quickly remembers how most of us really feel most of the time? (bipolar)

![4611CA1C-6D06-4522-BC1C-AE35A04E06E7](https://user-images.githubusercontent.com/16600935/61179085-97bfb680-a5b8-11e9-85c6-ff96f04186ba.jpeg)

**Comment by ccoenen** [comment]
I think the dog part alone would drastically change the way this comes across. But the essence of this could be added as a trait.

**Comment by Tropicalrambler** [comment]
This image helps graphically represent the following specific trait:

<img width="598" alt="Screen Shot 2019-07-18 at 5 31 24 PM" src="https://user-images.githubusercontent.com/16600935/61498837-28641100-a982-11e9-853c-9f771e93801d.png" alt="Can feel like an impostor at times.">


It also supports:
- Has productive and unproductive days
- Can be a slow coder.
- Doesn't take themselves too seriously

**Comment by cherscarlett** [comment]
Hey @Tropicalrambler! Thank you for this suggestion. Unfortunately this image doesn't really fit with the theme of the design of the site. If you find art that is more in line with the art theme, please feel free to open a PR. ❤️
