### ISSUE TITLE
Writes code that &emdash; gasp &emdash; has bugs.

### ISSUE THREAD

**Issue by rleddy** [cutenode/1x.engineer#134]
&emdhash does not seem to turn into a character. 

Also, I think this particular statement defeats the purpose of what you trying to accomplish.

It might be better to say that when a bug happens that the engineer is not belittled, berated, or fired by people who don't really lift a finger to do all the work. Or, something along those lines. 

Otherwise, such an engineer should avoid bugs by appropriately planning, documenting, and testing code. 

---

I got kicked off a Google project last fall because GitHub expanded my one-line commit into three lines. Prior to that little GitHub trouble, I really did save the project by throwing away a weekend and fixing a bug that was troubling their deepest pocket customers. I did that earlier in the summer. I worked all weekend OK. I spent a bunch of that time in a coffee shop in Santa Cruz. But, the customer was threatening to end the project the next Tuesday. So, the bug was fixed by Monday. 

(I was thinking of fixing the commit message on the next morning - a process that takes about an hour if you don't clone the repository - but, the guy fired off letters to managers with screenshots and everything before I could address it. The guy was out for blood. And, Google managers gave it to him.)

Later, the guys who got ahold of the project changed all the permissions on GitHub to make it difficult to commit changes. They very pointedly reminded me that programming these days is about "getting along with people".  But, that seemed to mean that the people had to come from the same town in India and perhaps attended the same school as the guys who took on the task of scolding me and playing around with the permissions. Also, it seemed to mean that all the work went to Bombay and that I was not supposed to do any real work but write their tests and fix up their test harnesses. And, I did that. I even went out of my way to give credit to guys who didn't get their work done to make the tests run on Travis and cover all the code that was supposed to be covered.

(Why not just clone the repository? I did not get time to. Also, I had not gone down the road of the closed of permissions with the repository forking. What if I killed my repository and no longer had permission to clone? I just didn't have that fact handy. But, Bombay guys were certainly the kind of guys who get pleasure in making it so that someone outside of their club would lose their workflow forever.)

Since the guys from Bombay wanted a great work-life balance it meant that if they wrote buggy code at a very slow pace, then that code was good. But, if I busted my butt to write good code, leave in comments, and write tests, then that code was really bad. So, where was my work-life balance?

It all was seasoned by managers, Americans, from Colorado who are the kind of guys who like to do the meetings and make project rules and still have ample time for their ball games. Since they are so cool and have such great work-life balance, they did not have to take time to really understand the project and if the GitHub rules caused some trouble -- well, that was SOME trouble. Truly the Colorado guys were way more into their ball game than into working projects. But, maybe that is a great work-life balance, right?

So, you see I like 1x. But, I don't like it when it means that people can be prejudiced, agist, and lazy. And, then the group of guys can fire people who are too in the way of their great plans, whatever those are. Maybe it's to keep a job while staying drunk or to climb the ladder or be the biggest bigot in the room.

Why the one-line commits? I got from another American, who was fired by the same guys, that it had to do with giving credit to the Bombay guys while masking the work of other people. The managers just look at the commits and see how many and who did them. That is their measure of performance. So, allowing Americans one-line commits that say something wimpy while allowing their Bombay friends many little commits over pointless details all called out in grandiose language fits the bill. 

Since I left, I have seen commit messages for changing spaces in log messages. And, I have seen bug reports indicating memory leaks, broken installations, destroyed Docker containers, and more. Also, they wrecked the security mechanisms by exposing keys and secrets all the while saying that they have enhanced security.

So, they have great high paying jobs, great work-life balance. And, now my work-life balance is great, too. I don't have a job and I am on unemployment.

I was thinking there might be a 5x programmer. Something in between the extremes. 

But, a lot of 1x stuff is good.  

There needs to be something about creating a plan for coding, designing algorithms ahead of coding, etc.  I have been forced too many times to just start writing code. Managers think that they are hot-shots and that a programmer's life is something that can be pushed around with trial and error.

**Comment by bnb** [comment]
Appreciate the time and effort you put into this. If you would like to make a PR to add your recommendation, please feel free! The &emdash; is intentional (see #9) and will remain.
