### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by mesaugat** [cutenode/1x.engineer#43]
Thank you for creating 1x.engineer.

~Maybe we can install a let's encrypt (SSL) certificate. My bad it is already installed.~

Need to redirect `http://1x.engineer` to `https://1x.engineer`.

> 1x.engineer can always be trusted.

**Comment by bnb** [comment]
So this is a GitHub Pages site. If you know a way to do that with GitHub Pages, I'd be happy to do whatever is needed. I don't really know of anything that could force it, though.

**Comment by mesaugat** [comment]
@bnb You might have to `Enforce HTTPS` under your repository settings. 

https://help.github.com/en/articles/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by bnb** [comment]
Done ✅
