### ISSUE TITLE
What about tests?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [cutenode/1x.engineer#49]
I think this this similar to docs - some people do, and some don't. What does everyone think?

**Comment by akanshgulati** [comment]
1x does not write tests. Test cases are part of 1.5x engineers.

**Comment by bnb** [comment]
IMO testing is a fundamental part of modern engineering. That said, some teams may not have tests as a core piece of how they approach projects and as such may not have their engineers write tests. I'd say this could be a good addition if it's not a required one.

**Comment by ccoenen** [comment]
tries to push towards more structured testing, but is really chill about it.

**Comment by vmussato** [comment]
I guess you must to be willing to learn tests. To say that you dont do tests cause you're code never breaks its a pretty arrogant statement.
