### ISSUE TITLE
Font isn't very readable

### ISSUE THREAD

**Issue by josh-perry** [cutenode/1x.engineer#52]
This is entirely subjective but I find the site's font difficult to read. It seems a bit too wide for comfort.

Might just be me :)

**Comment by bnb** [comment]
You are not the only person who has mentioned this. I'd be super interested in a font toggle for this exact purpose – someone has already expressed interest in contributing this – but I don't have time for this *today*. More than open to PRs that can keep the font in-tact for those that it works for and switch it for those that it doesn't.

**Comment by EtienneDepaulis** [comment]
Comic Sans MS would be awesome guys ! Cheers

**Comment by ccoenen** [comment]
Dingbatz or Windings

**Comment by dolanor** [comment]
Comic Sans MS would be very 1x.

**Comment by bnb** [comment]
Going to close this since it's been addressed with the switcher
