### ISSUE TITLE
Subjective - macOS - disable font smoothing?

### ISSUE THREAD

**Issue by runofthemill** [cutenode/1x.engineer#94]
First off - love the site! 

I noticed the headers (on fancy style) looked a bit blurry in Chrome on macOS, so was going to open a PR just to add `-webkit-font-smoothing: none;`, then thought about adding it to the `body` selector instead of `h1`/`h2`/etc., but since it's subjective, maybe you like as-is!

Take a look at the below screenshots (probably need to click thru to see the differences clearly) and let me know if you'd like a PR for either of the two changes?

Cheers!

As-is:
![Screen Shot 2019-07-31 at 11 58 16 AM](https://user-images.githubusercontent.com/8418440/62240065-02c80600-b38b-11e9-84fb-02f90212831a.png)

`-webkit-font-smoothing: none;` applied to `<body>`:
![Screen Shot 2019-07-31 at 11 59 23 AM](https://user-images.githubusercontent.com/8418440/62240087-09567d80-b38b-11e9-9601-7ef4e1254156.png)

`-webkit-font-smoothing: none;` applied to `<h1>`/`<h2>`:
![Screen Shot 2019-07-31 at 12 01 16 PM](https://user-images.githubusercontent.com/8418440/62240135-212e0180-b38b-11e9-9ea2-76c51339f9fe.png)

**Comment by bnb** [comment]
More than happy to merge this if you want to PR!
